package com.github.stevestorey.claudeanalyser.model;

/**
 * USD price per one million tokens for one model family, broken out by the
 * five things Anthropic charges for separately:
 *   - input         : regular prompt tokens
 *   - output        : tokens generated by the model
 *   - cacheWrite5m  : prompt-cache writes with 5-minute TTL (cheaper)
 *   - cacheWrite1h  : prompt-cache writes with 1-hour TTL (pricier)
 *   - cacheRead     : prompt-cache reads (very cheap)
 *
 * Cost in USD = tokens * rate / 1_000_000. See {@code Pricing} for the actual
 * per-family numbers and the model-name → rates mapping.
 */
public record ModelRates(
        double input,
        double output,
        double cacheWrite5m,
        double cacheWrite1h,
        double cacheRead) {

    /** Sentinel returned for unknown / non-Anthropic models so they cost $0. */
    public static final ModelRates ZERO = new ModelRates(0, 0, 0, 0, 0);
}
